[package]
name = "sqlparser_bench"
version = "0.1.0"
authors = ["Dandandan <danielheres@gmail.com>"]
edition = "2018"

[dependencies]
turso_sqlite3_parser = { path = "..", default-features = false, features = [
    "YYNOERRORRECOVERY",
    "NDEBUG",
] }
fallible-iterator = "0.3"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "sqlparser_bench"
harness = false
